/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class BlockchainConfig14 (

    @SerialName(value = "masterchain_block_fee")
    val masterchainBlockFee: kotlin.Long,

    @SerialName(value = "basechain_block_fee")
    val basechainBlockFee: kotlin.Long

) {


}

