/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.Method
import io.tonapi.models.Source

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class BlockchainAccountInspect (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "code_hash")
    val codeHash: kotlin.String,

    @SerialName(value = "methods")
    val methods: kotlin.collections.List<Method>,

    @SerialName(value = "compiler")
    val compiler: BlockchainAccountInspect.Compiler,

    @SerialName(value = "disassembled_code")
    val disassembledCode: kotlin.String? = null,

    @SerialName(value = "source")
    val source: Source? = null

) {

    /**
     * 
     *
     * Values: func,fift,tact
     */
    @Serializable
    enum class Compiler(val value: kotlin.String) {
        @SerialName(value = "func") func("func"),
        @SerialName(value = "fift") fift("fift"),
        @SerialName(value = "tact") tact("tact");
    }

}

