/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class BlockchainConfig45ContractsInner (

    @SerialName(value = "code_hash")
    val codeHash: kotlin.String,

    @SerialName(value = "gas_usage")
    val gasUsage: kotlin.Long

) {


}

