/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.ExecGetMethodArgType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class ExecGetMethodArg (

    @Contextual @SerialName(value = "type")
    val type: ExecGetMethodArgType,

    /* String representation of the value according to the specified type */
    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

