/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.EcPreview
import io.tonapi.models.EncryptedComment

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class ExtraCurrencyTransferAction (

    @SerialName(value = "sender")
    val sender: AccountAddress,

    @SerialName(value = "recipient")
    val recipient: AccountAddress,

    /* amount in quanta of tokens */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "currency")
    val currency: EcPreview,

    @SerialName(value = "comment")
    val comment: kotlin.String? = null,

    @SerialName(value = "encrypted_comment")
    val encryptedComment: EncryptedComment? = null

) {


}

