/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.JettonVerificationType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class JettonPreview (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "symbol")
    val symbol: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.Int,

    @SerialName(value = "image")
    val image: kotlin.String,

    @Contextual @SerialName(value = "verification")
    val verification: JettonVerificationType,

    @SerialName(value = "score")
    val score: kotlin.Int,

    @SerialName(value = "custom_payload_api_uri")
    val customPayloadApiUri: kotlin.String? = null

) {


}

