/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.JettonPreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


@Serializable

data class JettonSwapAction (

    @SerialName(value = "dex")
    val dex: JettonSwapAction.Dex,

    @SerialName(value = "amount_in")
    val amountIn: kotlin.String,

    @SerialName(value = "amount_out")
    val amountOut: kotlin.String,

    @SerialName(value = "user_wallet")
    val userWallet: AccountAddress,

    @SerialName(value = "router")
    val router: AccountAddress,

    @SerialName(value = "ton_in")
    val tonIn: kotlin.Long? = null,

    @SerialName(value = "ton_out")
    val tonOut: kotlin.Long? = null,

    @SerialName(value = "jetton_master_in")
    val jettonMasterIn: JettonPreview? = null,

    @SerialName(value = "jetton_master_out")
    val jettonMasterOut: JettonPreview? = null

) {

    /**
     * 
     *
     * Values: stonfi,dedust,megatonfi.unknown
     */
    @Serializable(with = DexSerializer::class)
    enum class Dex(val value: kotlin.String) {
        @SerialName(value = "stonfi") stonfi("stonfi"),
        @SerialName(value = "dedust") dedust("dedust"),
        @SerialName(value = "megatonfi") megatonfi("megatonfi"),
        @SerialName(value = "unknown") unknown("unknown");
    }

    internal object DexSerializer : KSerializer<Dex> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Dex {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Dex.entries.firstOrNull { it.value == value }
                ?: Dex.unknown
        }

        override fun serialize(encoder: Encoder, value: Dex) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

