/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.ImagePreview
import io.tonapi.models.NftItemCollection
import io.tonapi.models.Sale
import io.tonapi.models.TrustType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class NftItem (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "index")
    val index: kotlin.Long,

    /* Collection master contract confirmed that this item is part of collection */
    @SerialName(value = "verified")
    val verified: kotlin.Boolean,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, io.JsonAny>,

    /* Please use trust field */
    @SerialName(value = "approved_by")
    @Deprecated(message = "This property is deprecated.")
    val approvedBy: kotlin.collections.List<NftItem.ApprovedBy>,

    @Contextual @SerialName(value = "trust")
    val trust: TrustType,

    @SerialName(value = "owner")
    val owner: AccountAddress? = null,

    @SerialName(value = "collection")
    val collection: NftItemCollection? = null,

    @SerialName(value = "sale")
    val sale: Sale? = null,

    @SerialName(value = "previews")
    val previews: kotlin.collections.List<ImagePreview>? = null,

    @SerialName(value = "dns")
    val dns: kotlin.String? = null,

    @SerialName(value = "include_cnft")
    val includeCnft: kotlin.Boolean? = null

) {

    /**
     * Please use trust field
     *
     * Values: getgems,tonkeeper
     */
    @Serializable
    enum class ApprovedBy(val value: kotlin.String) {
        @SerialName(value = "getgems") getgems("getgems"),
        @SerialName(value = "tonkeeper") tonkeeper("tonkeeper");
    }

}

