/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.NftItem
import io.tonapi.models.Price

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class NftPurchaseAction (

    @SerialName(value = "auction_type")
    val auctionType: NftPurchaseAction.AuctionType,

    @SerialName(value = "amount")
    val amount: Price,

    @SerialName(value = "nft")
    val nft: NftItem,

    @SerialName(value = "seller")
    val seller: AccountAddress,

    @SerialName(value = "buyer")
    val buyer: AccountAddress

) {

    /**
     * 
     *
     * Values: DNSPeriodTon,DNSPeriodTg,NUMBERPeriodTg,getgems
     */
    @Serializable
    enum class AuctionType(val value: kotlin.String) {
        @SerialName(value = "DNS.ton") DNSPeriodTon("DNS.ton"),
        @SerialName(value = "DNS.tg") DNSPeriodTg("DNS.tg"),
        @SerialName(value = "NUMBER.tg") NUMBERPeriodTg("NUMBER.tg"),
        @SerialName(value = "getgems") getgems("getgems");
    }

}

