/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class Refund (

    @SerialName(value = "type")
    val type: Refund.Type,

    @SerialName(value = "origin")
    val origin: kotlin.String

) {

    /**
     * 
     *
     * Values: DNSPeriodTon,DNSPeriodTg,GetGems
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "DNS.ton") DNSPeriodTon("DNS.ton"),
        @SerialName(value = "DNS.tg") DNSPeriodTg("DNS.tg"),
        @SerialName(value = "GetGems") GetGems("GetGems");
    }

}

