/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class SourceFile (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "content")
    val content: kotlin.String,

    @SerialName(value = "is_entrypoint")
    val isEntrypoint: kotlin.Boolean,

    @SerialName(value = "is_std_lib")
    val isStdLib: kotlin.Boolean,

    @SerialName(value = "include_in_command")
    val includeInCommand: kotlin.Boolean

) {


}

