/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * Values: TransOrd,TransTickTock,TransSplitPrepare,TransSplitInstall,TransMergePrepare,TransMergeInstall,TransStorage
 */
@Serializable
enum class TransactionType(val value: kotlin.String) {

    @SerialName(value = "TransOrd")
    TransOrd("TransOrd"),

    @SerialName(value = "TransTickTock")
    TransTickTock("TransTickTock"),

    @SerialName(value = "TransSplitPrepare")
    TransSplitPrepare("TransSplitPrepare"),

    @SerialName(value = "TransSplitInstall")
    TransSplitInstall("TransSplitInstall"),

    @SerialName(value = "TransMergePrepare")
    TransMergePrepare("TransMergePrepare"),

    @SerialName(value = "TransMergeInstall")
    TransMergeInstall("TransMergeInstall"),

    @SerialName(value = "TransStorage")
    TransStorage("TransStorage");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TransactionType) "$data" else null

        /**
         * Returns a valid [TransactionType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TransactionType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

