/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.tonapi.models

import io.tonapi.models.AccountAddress
import io.tonapi.models.JettonPreview

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class ValueFlowJettonsInner (

    @SerialName(value = "account")
    val account: AccountAddress,

    @SerialName(value = "jetton")
    val jetton: JettonPreview,

    @SerialName(value = "qty")
    val qty: kotlin.String,

    @SerialName(value = "quantity")
    @Deprecated(message = "This property is deprecated.")
    val quantity: kotlin.Long

) {


}

