/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class ApplyPromoRequest (

    @SerialName(value = "public_key")
    val publicKey: kotlin.String,

    @SerialName(value = "promo_code")
    val promoCode: kotlin.String

) {


}

