/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.CreatePromoCampaign200ResponseParticipantsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class CreatePromoCampaign200Response (

    @SerialName(value = "participants")
    val participants: kotlin.collections.List<CreatePromoCampaign200ResponseParticipantsInner>

) {


}

