/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class CreatePromoCampaign200ResponseParticipantsInner (

    @SerialName(value = "address")
    val address: kotlin.String,

    @SerialName(value = "balance_increased")
    val balanceIncreased: kotlin.String? = null,

    @SerialName(value = "error")
    val error: kotlin.String? = null

) {


}

