/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class EnterpriseEstimate200Response (

    @SerialName(value = "estimated_upfront_payment")
    val estimatedUpfrontPayment: kotlin.String,

    /* base64 encoded emulation results. The exact type can be taken from /v2/wallet/emulate (TONAPI). */
    @SerialName(value = "emulation")
    val emulation: kotlin.String? = null

) {


}

