/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class EnterpriseGetMessage200Response (

    @SerialName(value = "status")
    val status: EnterpriseGetMessage200Response.Status,

    @SerialName(value = "payment_tx_hash")
    val paymentTxHash: kotlin.String? = null,

    @SerialName(value = "committed_tx_hash")
    val committedTxHash: kotlin.String? = null,

    @SerialName(value = "final_cost")
    val finalCost: kotlin.String? = null,

    @SerialName(value = "failed_reason")
    val failedReason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: pending,completed,failed
     */
    @Serializable
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "pending") pending("pending"),
        @SerialName(value = "completed") completed("completed"),
        @SerialName(value = "failed") failed("failed");
    }

}

