/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models

import io.batteryapi.models.EstimatedTronTxInstantFeeAcceptedAssetsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class EstimatedTronTxInstantFee (

    @SerialName(value = "fee_address")
    val feeAddress: kotlin.String,

    @SerialName(value = "accepted_assets")
    val acceptedAssets: kotlin.collections.List<EstimatedTronTxInstantFeeAcceptedAssetsInner>

) {


}

