/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class EstimatedTronTxInstantFeeAcceptedAssetsInner (

    @SerialName(value = "type")
    val type: EstimatedTronTxInstantFeeAcceptedAssetsInner.Type,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "amount_nano")
    val amountNano: kotlin.String,

    @SerialName(value = "decimals")
    val decimals: kotlin.Int,

    @SerialName(value = "jetton_master_id")
    val jettonMasterId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: jetton,ton
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "jetton") jetton("jetton"),
        @SerialName(value = "ton") ton("ton");
    }

}

