/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class IncreaseUserBalanceRequest (

    /* amount in TON to increase balance by */
    @SerialName(value = "amount")
    val amount: kotlin.String,

    /* reason for balance increase */
    @SerialName(value = "reason")
    val reason: kotlin.String? = null

) {


}

