/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.batteryapi.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual


@Serializable

data class TronTransactionsListTransactionsInner (

    @SerialName(value = "txid")
    val txid: kotlin.String,

    @SerialName(value = "from_account")
    val fromAccount: kotlin.String,

    @SerialName(value = "to_account")
    val toAccount: kotlin.String,

    @SerialName(value = "amount")
    val amount: kotlin.String,

    @SerialName(value = "is_pending")
    val isPending: kotlin.Boolean,

    @SerialName(value = "is_failed")
    val isFailed: kotlin.Boolean,

    @SerialName(value = "battery_charges")
    val batteryCharges: kotlin.Int,

    @SerialName(value = "timestamp")
    val timestamp: kotlin.Long,

    @SerialName(value = "trongrid_result")
    val trongridResult: kotlin.Int? = null

) {


}

